name: 'OPA Policy Check'

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to Terraform directory to scan (relative)'
        required: false
        default: 'trivy-demo'

permissions:
  contents: read

jobs:
  opa-conftest-scan:
    name: 'OPA Conftest Scan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -no-color -out=tfplan.binary

      - name: 'Convert plan to JSON'
        id: plan-json
        run: terraform show -json tfplan.binary > tfplan.json

      - name: 'Run OPA Scan with Conftest'
        uses: open-policy-agent/conftest-action@v0.62.0
        with:
          policy: policy # Directory containing your .rego files
          input: tfplan.json
