name: 'OPA Policy Check'

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to Terraform directory to scan (relative)'
        required: false
        default: 'trivy-demo'

jobs:
  opa-check:
    runs-on: ubuntu-latest
    name: Run OPA
    env:
      AWS_EC2_METADATA_DISABLED: 'true'
      AWS_ACCESS_KEY_ID: 'DUMMY'
      AWS_SECRET_ACCESS_KEY: 'DUMMY'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform plan (non-interactive, fallback)
        working-directory: ${{ github.event.inputs.path }}
        run: |
          terraform init -backend=false -input=false || true
          terraform plan -out=tfplan.binary -refresh=false -input=false || true
          # Capture terraform show output into a temp file
          terraform show -json tfplan.binary > tfplan.tmp 2>&1 || true
          # Robust extraction: use helper script to extract JSON from tfplan.tmp into tfplan.candidate
          python .github/scripts/extract_json.py tfplan.tmp tfplan.candidate || true
          echo "--- debug: sizes and md5 of tmp vs candidate ---"
          wc -c tfplan.tmp || true
          wc -c tfplan.candidate || true
          if command -v md5sum >/dev/null 2>&1; then md5sum tfplan.tmp tfplan.candidate || true; fi
          echo "--- debug: head (first 300 bytes) of tfplan.tmp ---" || true
          head -c 300 tfplan.tmp || true
          echo "--- debug: head (first 300 bytes) of tfplan.candidate ---" || true
          head -c 300 tfplan.candidate || true
          echo "--- debug: sizes (bytes) of tfplan.tmp and tfplan.candidate ---"
          wc -c tfplan.tmp || true
          wc -c tfplan.candidate || true
          # Prefer the raw tmp if it is valid JSON, otherwise fall back to the extracted candidate
          if jq -e . tfplan.tmp >/dev/null 2>&1; then
            mv tfplan.tmp tfplan.json
          elif jq -e . tfplan.candidate >/dev/null 2>&1; then
            mv tfplan.candidate tfplan.json
          else
            echo "Warning: terraform show did not produce valid JSON; saving raw output to tfplan.raw and using '{}' for tfplan.json" >&2
            mv tfplan.tmp tfplan.raw || true
            echo '{}' > tfplan.json
          fi

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 'v0.45.0'

      - name: Run OPA (evaluate policy/ against plan)
        working-directory: ${{ github.event.inputs.path }}
        run: |
          set -euo pipefail
          if [ ! -f tfplan.json ]; then
            echo '{}' > tfplan.json
          fi
          # Normalize tfplan.json: if it's an array, decide whether it looks like
          # plan-style resource_changes or show-style resources and wrap accordingly.
          if [ "$(jq -r 'type' tfplan.json)" = "array" ]; then
            echo "tfplan.json is an array; inspecting first element to normalize"
            first_type=$(jq -r '.[0] | keys_unsorted[0] // ""' tfplan.json)
            # Heuristic: if elements have 'change' or 'address' it's likely plan-style resource_changes
            if jq -r '.[0] | has("change") or has("address")' tfplan.json | grep -q true; then
              echo "Wrapping array as resource_changes"
              jq '{resource_changes: .}' tfplan.json > tfplan.normalized.json && mv tfplan.normalized.json tfplan.json
            else
              echo "Wrapping array as planned_values.root_module.resources"
              jq '{planned_values: {root_module: {resources: .}}}' tfplan.json > tfplan.normalized.json && mv tfplan.normalized.json tfplan.json
            fi
          fi
          echo "Running OPA eval against tfplan.json using policies in ../policy/"
          echo "--- debug: tfplan.json top-level keys ---"
          jq 'keys' tfplan.json || true
          echo "--- debug: resource_changes summary (address,type,actions,after.tags,after.tags_all) ---"
          jq -c '.resource_changes[]? | {address: .address, type: .type, actions: .change.actions, after_tags: .change.after.tags, after_tags_all: .change.after.tags_all}' tfplan.json || true
          echo "--- debug: planned_values.root_module.resources summary (address,type,values.tags,values.tags_all) ---"
          jq -c '.planned_values.root_module.resources[]? | {address: .address, type: .type, values_tags: .values.tags, values_tags_all: .values.tags_all}' tfplan.json || true
          echo "--- debug: policy files present in ../policy ---"
          ls -la ../policy || true
          echo "--- debug: head ../policy/tags.rego ---"
          head -n 200 ../policy/tags.rego || true
          echo "--- debug: head ../policy/demo_force_deny_universal.rego ---"
          head -n 200 ../policy/demo_force_deny_universal.rego || true
          # Output JSON for reliable parsing, and also save a pretty text copy
          opa eval --data ../policy/ --input tfplan.json 'data.terraform.deny' -f json > opa-results.json
          # Debug: produce an explanation trace to help see why rules didn't match
          opa eval --data ../policy/ --input tfplan.json 'data.terraform.deny' --explain full -f pretty > opa-explain.txt || true
          # Pretty-print for human logs
          jq '.' opa-results.json > opa-results.txt || cat opa-results.json > opa-results.txt
          echo "OPA JSON result saved to opa-results.json"
          # If denies exist, fail the step to make the CI actionable
          denys=$(jq '.[0].expressions[0].value | length' opa-results.json 2>/dev/null || echo 0)
          echo "denies_count=$denys"
          if [ "${denys}" != "0" ]; then
            echo "OPA found denies; see opa-results.txt"
            cat opa-results.txt
            exit 1
          else
            echo "No denies found by OPA"
            cat opa-results.txt
          fi

      - name: Upload OPA results
        uses: actions/upload-artifact@v4
        with:
          name: opa-results
          path: |
            ${{ github.event.inputs.path }}/tfplan.json
            ${{ github.event.inputs.path }}/opa-results.txt
            ${{ github.event.inputs.path }}/tfplan.tmp
            ${{ github.event.inputs.path }}/tfplan.candidate
            ${{ github.event.inputs.path }}/tfplan.raw
            ${{ github.event.inputs.path }}/opa-explain.txt
          if-no-files-found: warn
