name: 'OPA Policy Check'

on:
  pull_request:
    branches: [ main, master ]
    paths: [ 'terraform/**.tf', 'policy/**' ]

jobs:
  opa-check:
    runs-on: ubuntu-latest
    name: Run OPA
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform plan (non-interactive, fallback)
        working-directory: terraform/aws
        run: |
          terraform init -backend=false -input=false || true
          terraform plan -out=tfplan.binary -refresh=false -input=false || true
          terraform show -json tfplan.binary > tfplan.json || echo '{}' > tfplan.json

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 'v0.45.0'

      - name: Run OPA (evaluate policy/ against plan)
        working-directory: terraform/aws
        run: |
          if [ ! -f tfplan.json ]; then
            echo '{}' > tfplan.json
          fi
          opa eval --data ../policy/ --input tfplan.json 'data.terraform.deny' || true
