name: 'OPA Policy Check'

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to Terraform directory to scan (relative)'
        required: false
        default: 'trivy-demo'

jobs:
  opa-check:
    runs-on: ubuntu-latest
    name: Run OPA
    env:
      AWS_EC2_METADATA_DISABLED: 'true'
      AWS_ACCESS_KEY_ID: 'DUMMY'
      AWS_SECRET_ACCESS_KEY: 'DUMMY'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform plan (non-interactive, fallback)
        working-directory: ${{ github.event.inputs.path }}
        run: |
          terraform init -backend=false -input=false || true
          terraform plan -out=tfplan.binary -refresh=false -input=false || true
          terraform show -json tfplan.binary > tfplan.json || echo '{}' > tfplan.json

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 'v0.45.0'

      - name: Run OPA (evaluate policy/ against plan)
        working-directory: ${{ github.event.inputs.path }}
        run: |
          set -euo pipefail
          if [ ! -f tfplan.json ]; then
            echo '{}' > tfplan.json
          fi
          echo "Running OPA eval against tfplan.json using policies in ../policy/"
          # Output JSON for reliable parsing, and also save a pretty text copy
          opa eval --data ../policy/ --input tfplan.json 'data.terraform.deny' -f json > opa-results.json
          # Pretty-print for human logs
          jq '.' opa-results.json > opa-results.txt || cat opa-results.json > opa-results.txt
          echo "OPA JSON result saved to opa-results.json"
          # If denies exist, fail the step to make the CI actionable
          denys=$(jq '.[0].expressions[0].value | length' opa-results.json 2>/dev/null || echo 0)
          echo "denies_count=$denys"
          if [ "${denys}" != "0" ]; then
            echo "OPA found denies; see opa-results.txt"
            cat opa-results.txt
            exit 1
          else
            echo "No denies found by OPA"
            cat opa-results.txt
          fi

      - name: Upload OPA results
        uses: actions/upload-artifact@v4
        with:
          name: opa-results
          path: |
            ${{ github.event.inputs.path }}/tfplan.json
            ${{ github.event.inputs.path }}/opa-results.txt
          if-no-files-found: warn
