name: 'OPA Policy Check'

on:
  workflow_dispatch:
    inputs:
      terraform_path:
        description: 'Path to scan (relative)'
        required: true
        default: 'terraform/aws'

jobs:
  opa-check:
    name: 'Run OPA Policy Check'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Debug: list terraform path'
        run: |
          TF_PATH="${{ github.event.inputs.terraform_path || 'terraform/aws' }}"
          echo "Listing files in $TF_PATH"
          ls -la "$TF_PATH" || true

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: 'Terraform Init'
        working-directory: ${{ github.event.inputs.terraform_path || 'terraform/aws' }}
        env:
          TF_IN_AUTOMATION: 1
        run: terraform init -backend=false -input=false
        # Add environment variables for cloud provider credentials if needed for the plan
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Terraform Plan'
        working-directory: ${{ github.event.inputs.terraform_path || 'terraform/aws' }}
        env:
          TF_IN_AUTOMATION: 1
        run: |
          # Run plan but never fail the workflow if plan can't complete (no creds etc.)
          terraform plan -input=false -out=tfplan.binary || true

      - name: 'Convert plan to JSON'
        working-directory: ${{ github.event.inputs.terraform_path || 'terraform/aws' }}
        env:
          TF_IN_AUTOMATION: 1
        run: |
          # Convert plan to JSON if possible; if not, create an empty JSON to let OPA run harmlessly
          if [ -f tfplan.binary ]; then
            terraform show -json tfplan.binary > tfplan.json || echo '{}' > tfplan.json
          else
            echo '{}' > tfplan.json
          fi

      - name: 'Set up OPA'
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: 'Run OPA evaluation (non-failing)'
        run: |
          TF_PATH="${{ github.event.inputs.terraform_path || 'terraform/aws' }}"
          TF_PLAN_JSON="$TF_PATH/tfplan.json"
          # Evaluate policies but do not fail the workflow. Print any violations if present.
          if [ -f "$TF_PLAN_JSON" ]; then
            results=$(opa eval --data policy/ --input "$TF_PLAN_JSON" 'data.terraform.deny') || true
          else
            results=$(opa eval --data policy/ --input <(echo '{}') 'data.terraform.deny') || true
          fi

          if [ -n "$results" ]; then
            echo "OPA Policy Violations Found:"
            echo "$results"
          else
            echo "OPA policies passed or no data to evaluate."
          fi
