name: 'Terrascan Scan'

on:
  workflow_dispatch:
    inputs:
      terraform_path:
        description: 'Path to scan (relative)'
        required: true
        default: 'terraform/'

permissions:
  contents: read
  security-events: write

jobs:
  terrascan:
    name: 'Run Terrascan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Run Terrascan'
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          iac_dir: '${{ github.event.inputs.terraform_path }}'
          policy_type: 'aws'
          sarif_upload: true
          only_warn: true

      - name: 'Upload SARIF file to GitHub Security tab'
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() }}
        with:
          sarif_file: terrascan.sarif
