name: Terraform Compliance

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to Terraform directory to scan (relative)'
        required: false
        default: 'trivy-demo'
permissions:
  contents: read

jobs:
  terraform-compliance-scan:
    name: 'Terraform Compliance Scan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        id: init
        run: terraform init

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -out tfplan.binary

      - name: 'Run Terraform Compliance'
        uses: terraform-compliance/github-action@v0.3.0
        with:
          plan-file: './tfplan.binary'
          feature-file: 'features' # Directory containing your .feature files
