name: 'Terraform Linting'

on:
  workflow_dispatch:
    inputs:
      terraform_path:
        description: 'Path to scan (relative)'
        required: true
        default: 'terraform/'

jobs:
  tflint:
    name: 'Run TFLint'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Cache TFLint plugin directory'
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tflint-

      - name: 'Set up TFLint'
        uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: v0.52.0

      - name: 'Initialize TFLint'
        run: tflint --init
        env:
          # Use secrets.GITHUB_TOKEN to avoid rate-limiting when downloading plugins
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run TFLint scan'
        # Run in the requested path for workflow_dispatch, otherwise default to terraform/
        working-directory: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_path || 'terraform/' }}
        run: tflint --format compact