name: Trivy scan Terraform plan

on:
  workflow_dispatch

jobs:
  trivy-plan-scan:
    name: Generate Terraform plan and scan with Trivy
    runs-on: ubuntu-latest
    env:
      AWS_EC2_METADATA_DISABLED: 'true'
      AWS_ACCESS_KEY_ID: 'DUMMY'
      AWS_SECRET_ACCESS_KEY: 'DUMMY'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Change to demo directory
        run: |
          cd trivy-demo
          pwd

      - name: Terraform init
        working-directory: trivy-demo
        run: terraform init -backend=false

      - name: Terraform plan (binary)
        working-directory: trivy-demo
        run: terraform plan -out=tfplan.binary

      - name: Convert plan to JSON
        working-directory: trivy-demo
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Download Trivy image and scan plan JSON
        working-directory: trivy-demo
        run: |
          TRIVY_IMAGE=aquasec/trivy:0.52.2

          # Use the Trivy config command against the Terraform plan JSON and
          # output SARIF. This form is compatible with the pinned image and
          # produces `trivy.sarif` for artifact upload / code scanning.
          docker run --rm -v "$PWD":/work -w /work ${TRIVY_IMAGE} config tfplan.json -f sarif -o trivy.sarif

      - name: Upload tfplan.json and Trivy SARIF
        uses: actions/upload-artifact@v4
        with:
          name: trivy-plan-artifacts
          path: |
            trivy-demo/tfplan.json
            trivy-demo/trivy.sarif
          if-no-files-found: warn
